stockage:
  fichier:
    photos:
      produits: fichiers/photos/produits

server:
    servlet:
      context-path: /stock-expert

spring:
  application:
    name: backend-stock-expert

  profiles:
    active: ${APP_PROFILE}

  messages:
    basename: internationalisation/messages
    encoding: UTF-8

  mail:
    host: ${mail-host}
    port: ${mail-port}
    username: ${mail-username}
    password: ${mail-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


management:
  endpoints:
    web:
      exposure:
        include:
        - bean
        - metrics
  
    
    

      

